config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length:{minimum:3, maximum: 50}
  validates :description, presence: true, length:{minimum:3, maximum: 500}
  validates :user_id, presence: true
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 25, minimum: 3}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :articles, dependent: :destroy
 
 before_save {self.email = email.downcase}
 validates :username, presence: true, uniqueness: {case_sensitive: false}, 
                     length: { minimum: 3, maximum: 35}
                 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                      
  validates :email, presence: true, uniqueness: {case_sensitive: false},
                   length: {maximum: 150}, format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.

  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

  
  def current_user
    user||= User.find(session[:user_id]) if session[:user_id]
    
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit, :show, :update , :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
    
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was saved successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
  
      if @article.update(article_params)
      flash[:success] = "Article was updated successfully"
      redirect_to article_path(@article)
      else
      render 'edit'
      end
  end
  
  def index
    @art = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "message was deleted"
    redirect_to articles_path
  end
  

  
  private
  
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
    def require_same_user
      if current_user != @article.user and !current_user.admin
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to articles_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:show, :index]
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def index 
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def show
  
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || logged_in? && !current_user.admin
      flash[:danger] = "Only admins can perform this action"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id]= @user.id
      flash[:success] = "You have logged in successfully"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "There is some error in your Log in information"
     render 'new' 
    end
    
    
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out, see you next time!"
    redirect_to root_path
  end
  
  
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:edit, :update, :show ]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def new
    @user = User.new
  end
  
  def index
      @user = User.paginate(page: params[:page],  per_page: 5)
  end
  
  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
      if @user.save
        flash[:success] = "Account successfully created, welcome to Alpha Blog #{@user.username}"
        redirect_to user_path(@user)
        
      else render 'new'
      
      end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Account updated!"
      redirect_to articles_path
     else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all user's articles have been deleted"
    redirect_to users_path
  end
  
  
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own user profile"
      redirect_to users_path
    
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for (user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"img-circle" )
  end
end

app/views/articles/_article.html.erb
  
<% obj.each do |m| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
            <%= link_to m.title, article_path(m) %>
        </div>
        <div class="article-description">
         <%= truncate(m.description, length: 100)%>
           <div class="article-meta-details">
             <small> Created by <%= m.user.username if m.user%>, 
                                <%= time_ago_in_words(m.created_at)%> ago. 
                     Updated at <%= time_ago_in_words(m.updated_at)%></small>
           </div>
        </div>
      <% if logged_in? && (current_user == m.user || current_user.admin?) %>
      <div class="article-actions">
        <%= link_to"edit this article", edit_article_path(m), class:"btn btn-xs btn-success"%>
        <%= link_to "Delete this article", article_path(m), method: :delete, data: { confirm: "Delete this?"}, class:"btn btn-xs btn-danger"%>
      </div>
      <% end %>
    </div>
  </div>
</div>
  
  <% end %>
  

app/views/articles/_forms.html.erb
<%= render "shared/errors", obj: @article%>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article,  :html => {class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :title, class: "form-control", placeholder: "Title goes here", autofocus: true %>
        </div>
      </div>
      <div class="form-group"> 
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
        <div class="col-sm-7">
          <%= f.text_area :description, rows:10, class: "form-control", placeholder: "Title goes here" %>
        </div>  
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class:'btn btn-primary btn-lg'%>
        </div>
      </div>
    <% end %> 
  </div>
</div>

<div class="col-sm-4 col-sm-offset-4">
  [ <%= link_to"Cancel and return to article listing", articles_path%> ]
</div>

app/views/articles/edit.html.erb
<h1 align= "center" style="width:90%;"> Edit your article here</h1>

<%= render 'forms' %>

app/views/articles/index.html.erb
<h1 align="center">Showing all articles</h1>
<div align="center">  <%= will_paginate(@art) %></div>

  
<%= render 'article', obj: @art%>
 
  <div align="center">  <%= will_paginate(@art) %></div>

app/views/articles/new.html.erb
<div>
<h1 align="center" style="width:90%;"> Create an Article</h1>
</div>
<%= render 'forms' %>

app/views/articles/show.html.erb
<h2 align="center" style="width:90%;"> Title: <%= @article.title%></h2>
 
  
<div class="row">
 <div class="well col-xs-8 col-xs-offset-2">
  <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <% if @article.user %>
          <ul class="listing">
           <li><strong>Created By: </strong></li>
            <% if @article.user.email %>
              <% gravure = gravatar_for(@article.user)%>
              <%= content_tag :li , (link_to gravure, user_path(@article.user))%>
            <% else %>
            <%end%>
            <li class="article-title">
              <%= link_to @article.user.username.capitalize, user_path(@article.user)%>
            </li>
            <li><small style="color:black;"><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles%> </small></li>
          </ul>
        <% end %>
      </div>
    </div>
    
   <h4 class="center description"> Description </h4> <hr> 
   <%= simple_format(@article.description)%>
  
    <div class="article-actions">
     <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
     <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Delete this?"}, class:"btn btn-xs btn-danger"%> 
     <%= link_to"edit this article", edit_article_path, class:"btn btn-xs btn-success"%>
     <%end%>
    <%= link_to"back to article listing", articles_path, class:"btn btn-xs btn-primary"%>
    </div> 
   
  </div>  
 </div>

app/views/categories/index.html.erb
<h1 align="center" style="width:95%;"> Listing all Category</h1>

<ul class="listing" align="center">
  <%= will_paginate %>
  <div class="row">
    <% @categories.each do |category|%>
    <div class=" well col-md-4 col-md-offset-4">
        <li class="article-title">
          <%= link_to "#{category.name}" , category_path(category)%> 
        </li>
     </div>
     <% end %>
  </div>
  <%= will_paginate %>
</ul>

app/views/categories/new.html.erb
<h1 align="center" style="width:90%;"> Create new Category</h1>

<%= render "shared/errors", obj: @category%>


    <%= form_for(@category,  :html => {class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter new Category", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class:'btn btn-primary btn-lg'%>
        </div>
      </div>
    <% end %> 

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small> Copyright &copy; Brought to you by <%=link_to'Toone', about_path%> </small>
  
  <nav>
    <ul>
      <li><%= link_to'All Article', articles_path%></li>
      <li><%= link_to'Create New', new_article_path%> </li>
    </ul>
  </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row>">
  <div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg|%>
  <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
  </div>
<% end %>


</div>
</div

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "Brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to"All Users", users_path%>></li>
        <% if logged_in? %>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path%></li>
              <li><%= link_to "All Users", users_path%></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Logout" , logout_path, method: :delete%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "ADMIN" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to"Edit your profile", edit_user_path(current_user)%></li>
              <li><%= link_to"Show your profile", users_path(current_user)%></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login" , login_path%></li>
          <li><%= link_to "Signup" , signup_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages' %>
    <div class="container div-check">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
    logged_in<%= debug(logged_in?) if Rails.env.development? %>
     current_user<%= debug(current_user) if Rails.env.development? %>
     @user<%= debug(@user) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is About </h1>

<%= link_to'Home', root_path%>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>~ALPHA BLOG~</h1>
  <%= link_to "Sign Up", signup_path, class:"btn btn-primary btn-lg btn-home"%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count,"error")%> detected, cannot save this article.
          </h2>
        </div>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li> 
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user%>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user,  :html => {class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Your Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group"> 
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
        <div class="col-sm-7">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email here." %>
        </div>  
      </div>
      <div class="form-group"> 
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
        <div class="col-sm-7">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter your password here." %>
        </div>  
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit (@user.new_record? ? "Sign up now": "Update your Account" ), class:'btn btn-primary btn-lg'%>
        </div>
      </div>
    <% end %> 
  </div>
</div>

<div class="col-sm-4 col-sm-offset-4">
  [ <%= link_to"Cancel and return to article listing", articles_path%> ]
</div>

app/views/users/edit.html.erb
<h1 align= "center" style="width:90%"> Edit your Account here</h1>
<%=render 'form' %>

app/views/users/index.html.erb
<h1 align= "center" style="width:90%"> All Alpha Bloggers</h1>
  <div align="center"> 
   <%= will_paginate (@user) %>
    <% @user.each do |user|%>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="well well-lg">
          <ul class="listing">
            <% if user.email %>
              <% gravure = gravatar_for(user)%>
              <%= content_tag :li , (link_to gravure, user_path(user))%>
            <% else %>
            <%end%>
            <li class="article-title">
              <%= link_to user.username.capitalize, user_path(user)%>
            </li>
            <li><small><%= pluralize(user.articles.count, 'article') if user.articles%> </small></li>
            <li><% if logged_in? and current_user.admin? %>
                  <%= link_to "Delete this user",user_path(user), method: :delete, data: { confirm: "Are you sure?? All data will be gone"} %>
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
 
  <% end %> 
   <%= will_paginate (@user)%>
  </div> 

app/views/users/new.html.erb
<h1 align= "center" style="width:90%">Sign up now to ALPHA BLOG!</h1>

<%=render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to your Profile page, <%= @user.username%> </h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user, 30 if @user.email %>
  </div>
</div>

<h4 align="center"> Showing all <%= @user.username%>'s article</h4>
<div align="center"><%= will_paginate (@user_articles) %></div>
<%= render'articles/article' , obj:@user_articles %>
<div align="center"><%= will_paginate (@user_articles) %></div>